### ISSUE TITLE
2.1 Selecting

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/jquery#1]
https://github.com/osifoanosike/jquery/tree/master/exercise2_1

2.1 Selecting
Open the file /exercises/index.html in your browser. Use the file /exercises/js/sandbox.js to accomplish the following:

Select all of the div elements that have a class of “module”.
Come up with three selectors that you could use to get the third item in the #myList unordered list. Which is the best to use? Why?
Select the label for the search input using an attribute selector.
Figure out how many elements on the page are hidden
Figure out how many image elements on the page have an alt attribute.
Select all of the odd table rows in the table body.

**Comment by abhishekjain16** [comment]
imagesWithAltAttr: function() {
    var $images = $('img'), count = 0;
    $images.each(function(index) {
      var img_attr = $(this).attr('alt');
      if ( img_attr !== undefined && img_attr !== false ) {
        count++;
      }
    });

this can be found with easier way

**Comment by osifoanosike** [comment]
Corrected
