### ISSUE TITLE
7.2. Create a stack of divs

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/jquery#12]
https://github.com/osifoanosike/jquery/tree/master/exercise7_2

Create a stack of divs. Initially an empty container should display- a button on right side says "add item", should add a div to the stack with an incremental number(starting from 1) - clicking any item in the stack should highlight that item- clicking the last item on the stack should remove that item from the stackhint: use jQuery delegate. live method has been removed from the latest version of jQuery so you may want to use on() or delegate()

**Comment by abhishekjain16** [comment]
Please read the question again, and discuss if you have any doubts.

**Comment by osifoanosike** [comment]
Corrected.
