### ISSUE TITLE
4.2 Add tabbed navigation.

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/jquery#5]
https://github.com/osifoanosike/jquery/tree/master/exercise4_2

4.2 Add tabbed navigation.
Open the file /exercises/index.html in your browser. Use the file /exercises/js/tabs.js. Your task is to create tabbed navigation for the two div.module elements. To accomplish this:

Hide all of the modules.
Create an unordered list element before the first module.
Iterate over the modules using $.fn.each. For each module, use the text of the h2 element as the text for a list item that you add to the unordered list element.
Bind a click event to the list item that:
Shows the related module, and hides any other modules
Adds a class of “current” to the clicked list item
Removes the class “current” from the other list item
Finally, show the first tab.

**Comment by yuktikhurana** [comment]
1. $('div.module') being repeated
2. use header_list
3. naming consitency. Please use CamelCase
4. set_current_item can be optimised
5. not a good example for using event delegation

**Comment by osifoanosike** [comment]
Corrected

**Comment by yuktikhurana** [comment]
remove the console.log code and close it

**Comment by osifoanosike** [comment]
Done, Thanks
