### ISSUE TITLE
5.1 Reveal hidden text.Open the file /exercises/index.html in your browser.

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/jquery#6]
https://github.com/osifoanosike/jquery/tree/master/exercise5_1

5.1 Reveal hidden text.Open the file /exercises/index.html in your browser. Use the file /exercises/js/blog.js. Your task is to add some interactivity to the blog section of the page. The spec for the feature is as follows:
Clicking on a headline in the #blog div should slide down the excerpt paragraph
Clicking on another headline should slide down its excerpt paragraph, and slide up any other currently showing excerpt paragraphs.

**Comment by Shruti2791** [comment]
Read  about addClass method. Use it instead of attr. This will enable you to add and remove specific classes instead of the entire attribute tag.

**Comment by osifoanosike** [comment]
Corrected. Thanks

**Comment by Shruti2791** [comment]
Looks good :+1:
