### ISSUE TITLE
5.2 Create Drop down menus.Open the file /exercises/index.html in your browser

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/jquery#7]
https://github.com/osifoanosike/jquery/tree/master/exercise5_2

5.2 Create Drop down menus.Open the file /exercises/index.html in your browser. 
Use the file /exercises/js/navigation.js. Your task is to add dropdowns to the main navigation at the top of the page.
Hovering over an item in the main menu should show that item's submenu items, if any.
Exiting an item should hide any submenu items.
To accomplish this, use the $.fn.hover method to add and remove a class from the submenu items to control whether they're visible or hidden. (The file at /exercises/css/styles.css includes the "hover" class for this purpose.)

**Comment by yuktikhurana** [comment]
1. code can be optimised

**Comment by osifoanosike** [comment]
Fixed

**Comment by yuktikhurana** [comment]
looks good
