### ISSUE TITLE
6.1 Load External Content

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/jquery#9]
https://github.com/osifoanosike/jquery/tree/master/exercise6_1

6.1 Load External Content
Open the file /exercises/index.html in your browser. Use the file /exercises/js/load.js. Your task is to load the content of a blog item when a user clicks on the title of the item.
Create a target div after the headline for each blog post and store a reference to it on the headline element using $.fn.data.
Bind a click event to the headline that will use the $.fn.load method to load the appropriate content from /exercises/data/blog.html into the target div. Don't forget to prevent the default action of the click event.

**Comment by mkangia** [comment]
Osifo why do we need to do '.data('target_div', $($target_div))' ?

**Comment by osifoanosike** [comment]
Corrected
